<?php

namespace Repository;

/**
 * GruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruntRepository extends \Doctrine\ORM\EntityRepository
{
    public function pobierzWszystko()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')->from('Entity\Grunt', 'm')->join('m.nieruchomosc', 'n');
        return $qb->getQuery()->getResult();
    }
}
